### ISSUE TITLE
Not loading in Jetbrains 2022

### ISSUE THREAD

**Issue by nuller1joe** [stasmarkin/KineticScroll-IDEA-plugin#1]
I absolutely love your plugin. I can't understand its not part of Jetbrains products by default.

However, the plugin does not load correctly. 

Every time I restart rider, I have to go to plug-ins, disable and then re-enable the plugin for it to work.
After "reloading" the plugin, it works flawless until rider is closed. Then it has to be reloaded again

**Comment by stasmarkin** [comment]
Thank you. 
It's an issue due to Jetbrains depricated some types of plugin loading, and I'm too lazy to learn new one. 
It's in my TODO , but I cant really estimate when I will have extra 4-6 hours to fix it.

But I feel really motivated to fix it sooner now )

**Comment by nuller1joe** [comment]
8 out of 11 programmers where I work use this plugin, so it would be highly appreciated at our company

**Comment by stasmarkin** [comment]
Resolved in 1.0.3, please check an update

**Comment by nuller1joe** [comment]
We really really appreciate the extra work you put into this! Thank you!

**Comment by nuller1joe** [comment]
Just checking back in again to let you know that this plugin is amazing!
